# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(blank=True)),
                ('kind', models.CharField(choices=[('1Noun', 'Noun'), ('2Adj', 'Adjective')], default='1Noun', max_length=24)),
                ('czech', models.CharField(max_length=120, unique=True)),
                ('german', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('czech', models.CharField(max_length=48, unique=True)),
                ('german', models.CharField(blank=True, max_length=48)),
                ('gender_cz', models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Feminine'), ('N', 'Neuter')], default='M', max_length=1)),
                ('gender_de', models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Feminine'), ('N', 'Neuter')], default='M', max_length=1)),
                ('animate', models.NullBooleanField()),
                ('dec', jsonfield.fields.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
