# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExNNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(blank=True)),
                ('czech', models.CharField(max_length=120, unique=True)),
                ('german', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AlterField(
            model_name='noun',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='noun',
            name='gender_cz',
            field=models.CharField(choices=[('M', 'Masculine'), ('F', 'Feminine'), ('N', 'Neuter')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='noun',
            name='gender_de',
            field=models.CharField(choices=[('M', 'Masculine'), ('F', 'Feminine'), ('N', 'Neuter')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='exnns',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Noun'),
        ),
    ]
