# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20171127_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exnns',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
