# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20171127_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='artikel',
            field=models.CharField(choices=[('M', 'der'), ('F', 'die'), ('N', 'das')], default='der', max_length=3),
            preserve_default=False,
        ),
    ]
