# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20171127_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noun',
            name='artikel',
        ),
    ]
