# Generated by Django 2.0.1 on 2018-01-22 20:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_exlns'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='de',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
