# Generated by Django 2.0.1 on 2018-01-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_noun_de'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noun',
            old_name='dec',
            new_name='cz',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='gender_cz',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='gender_de',
        ),
    ]
