# Generated by Django 2.0.1 on 2018-01-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_perspronoun'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspronoun',
            name='role',
            field=models.CharField(default='def', max_length=10),
            preserve_default=False,
        ),
    ]
