# Generated by Django 2.0.1 on 2018-01-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_exkkv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exaas',
            name='czech',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='exiiv',
            name='czech',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='exkkv',
            name='czech',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='exlns',
            name='czech',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='exnns',
            name='czech',
            field=models.CharField(max_length=120),
        ),
    ]
