# Generated by Django 2.0.1 on 2018-01-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20180130_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersPronoun',
        ),
        migrations.AlterField(
            model_name='exaas',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addwords.Noun'),
        ),
        migrations.AlterField(
            model_name='exiiv',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addwords.Verb'),
        ),
        migrations.AlterField(
            model_name='exkkv',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addwords.Verb'),
        ),
        migrations.AlterField(
            model_name='exlns',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addwords.Noun'),
        ),
        migrations.AlterField(
            model_name='exnns',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addwords.Noun'),
        ),
        migrations.DeleteModel(
            name='Noun',
        ),
        migrations.DeleteModel(
            name='Verb',
        ),
    ]
