# Generated by Django 2.0.1 on 2018-01-30 19:46

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('czech', models.CharField(max_length=48, unique=True)),
                ('german', models.CharField(blank=True, max_length=48)),
                ('animate', models.NullBooleanField()),
                ('cz', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('de', jsonfield.fields.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersPronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('czech', models.CharField(max_length=48, unique=True)),
                ('german', models.CharField(blank=True, max_length=48)),
                ('cz', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('de', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('role', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('czech', models.CharField(max_length=48, unique=True)),
                ('german', models.CharField(blank=True, max_length=48)),
                ('imperfect', models.NullBooleanField()),
                ('cz', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('de', jsonfield.fields.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
