# Generated by Django 2.0.1 on 2018-02-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perspronoun',
            name='cz',
        ),
        migrations.RemoveField(
            model_name='perspronoun',
            name='de',
        ),
        migrations.AlterField(
            model_name='perspronoun',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, '1st Sin'), (1, '2nd Sin'), (2, '3rd Sin'), (3, '1st Plu'), (4, '2nd Plu'), (5, '3rd Plu')], default=0),
        ),
    ]
