# Generated by Django 2.0.1 on 2018-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0002_auto_20180228_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspronoun',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Neuter')], default=0, max_length=6),
        ),
    ]
