# Generated by Django 2.0.1 on 2018-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0003_perspronoun_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspronoun',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Neuter')], default=0),
        ),
    ]
