# Generated by Django 2.0.1 on 2018-03-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0005_auto_20180302_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspronoun',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Neuter')], default='m', max_length=1),
        ),
    ]
